-- ===========================================================================
-- PIP-MLK baseline migration — init
-- Created: 2026-01-01T00:00:00Z
-- Reviewer: PIP-MLK platform team
--
-- This migration establishes the baseline schema (User + Post models) with
-- the indexes documented in docs/RESEARCH-DATABASE.md §5.
--
-- Generated by `prisma migrate dev --name init`. Do NOT edit by hand —
-- to change the schema, add a NEW migration via `prisma migrate dev --name <desc>`.
-- ===========================================================================

-- CreateTable: User
CREATE TABLE "User" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "email" TEXT NOT NULL,
    "name" TEXT,
    "role" TEXT NOT NULL DEFAULT 'analyst',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateTable: Post
CREATE TABLE "Post" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "title" TEXT NOT NULL,
    "content" TEXT,
    "published" BOOLEAN NOT NULL DEFAULT false,
    "authorId" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,

    CONSTRAINT "Post_authorId_fkey"
        FOREIGN KEY ("authorId") REFERENCES "User"("id")
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- Unique constraints
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- Single-column indexes — hot filter + sort paths
CREATE INDEX "User_role_idx"        ON "User"("role");
CREATE INDEX "User_createdAt_idx"   ON "User"("createdAt");

CREATE INDEX "Post_authorId_idx"    ON "Post"("authorId");
CREATE INDEX "Post_published_idx"   ON "Post"("published");
CREATE INDEX "Post_createdAt_idx"   ON "Post"("createdAt");
CREATE INDEX "Post_updatedAt_idx"   ON "Post"("updatedAt");

-- Composite index — supports dashboard list view:
-- "published posts by author, newest first"
CREATE INDEX "Post_authorId_published_createdAt_idx"
    ON "Post"("authorId", "published", "createdAt");
